"""01_initial-db

Revision ID: 79960a4080e6
Revises: a0319c09e5f8
Create Date: 2023-10-18 01:46:49.040805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79960a4080e6'
down_revision = 'a0319c09e5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_uuid', sa.String(length=96), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
