"""01_initial-db

Revision ID: a0319c09e5f8
Revises: 1c573bddce1b
Create Date: 2023-10-18 01:43:17.134155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0319c09e5f8'
down_revision = '1c573bddce1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
